apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
{{<- range $key, $value := .Values.kubeflow_tools.knative.domains >}}
  {{< $key >}}: |
  {{< $value | indent 2 >}}
{{<- end >}}