apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
  labels:
    app.kubernetes.io/component: net-istio
    app.kubernetes.io/name: knative-serving
data:
{{<- range $key, $value := .Values.kubeflow_tools.knative.istio.gateways >}}
  {{< $key >}}: {{< $value | quote >}}
{{<- end >}}