apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## global namespace must be set due to:
## https://github.com/kubernetes-sigs/kustomize/issues/1301#issuecomment-1308228710
#namespace: knative-serving

resources:
  ## upstream
  - upstream/kserve.yaml
  - upstream/kserve-cluster-resources.yaml
  - upstream/web-app/contrib/kserve/models-web-app/base
  - resources/webAppClusterRole.yaml
patchesStrategicMerge:
  - patches/patchKserveConfigMap.yaml
  - patches/patchWebAppIstioConfig.yaml
images:
- name: kserve/models-web-app
  newName: weystrom/models-web-app
  newTag: latest

configMapGenerator:
- literals:
  - APP_DISABLE_AUTH="True"
  - APP_PREFIX="/kserve-endpoints"
  name: kserve-models-web-app-config
  behavior: merge