apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kserve-models-web-app
  namespace: kserve
spec:
  gateways:
  - "{{< .Values.deploykf_core.deploykf_istio_gateway.namespace >}}/{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name >}}"
  hosts:
  - {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.hostname >}}