apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  credentials: |-
    {
       "storageSpecSecretName": "storage-config",
       "storageSecretNameAnnotation": "serving.kserve.io/storageSecretName",
       "gcs": {
           "gcsCredentialFileName": "gcloud-application-credentials.json"
       },
       "s3": {
           "s3AccessKeyIDName": "AWS_ACCESS_KEY_ID",
           "s3SecretAccessKeyName": "AWS_SECRET_ACCESS_KEY",
           "s3Endpoint": "",
           "s3UseHttps": "",
           "s3Region": "",
           "s3VerifySSL": "",
           "s3UseVirtualBucket": "",
           "s3UseAccelerate": "",
           "s3UseAnonymousCredential": "",
           "s3CABundle": ""
       }
    }
  ingress: |-
    {
        "ingressGateway" : "{{< .Values.deploykf_core.deploykf_istio_gateway.namespace >}}/{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name >}}",
        "ingressService" : "{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name >}}.{{< .Values.deploykf_core.deploykf_istio_gateway.namespace >}}.svc.cluster.local",
        "localGateway" : "{{< .Values.deploykf_core.deploykf_istio_gateway.namespace >}}/{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name >}}",
        "localGatewayService" : "{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name >}}.{{< .Values.deploykf_core.deploykf_istio_gateway.namespace >}}.svc.cluster.local",
        "ingressDomain"  : "{{< .Values.deploykf_core.deploykf_istio_gateway.gateway.hostname >}}",
        "ingressClassName" : "istio",
        "domainTemplate": "{{ .Name }}-{{ .Namespace }}.{{ .IngressDomain }}",
        "urlScheme": "https",
        "disableIngressCreation": true,
        "disableIstioVirtualHost": true
    }
  deploy: |-
    {
        "defaultDeploymentMode": "RawDeployment"
    }