open-webui:
  ollama:
    image:
      tag: "0.2.1"
    persistentVolume:
      enabled: true
      storageClass: "openebs-lvmpv"
      size: "200Gi"
    updateStrategy:
      type: "Recreate"
    extraEnv:
      - name: OLLAMA_FLASH_ATTENTION
        value: "1"
      - name: OLLAMA_KEEP_ALIVE
        value: "-1"
    ollama:
      models:
        - llama3:8b
      gpu:
        enabled: true
        number: 2
  ingress:
    enabled: false
  persistence:
    enabled: true
    storageClass: "openebs-lvmpv"
  extraEnvVars:
  - name: WEBUI_AUTH_TRUSTED_EMAIL_HEADER
    value: X-Forwarded-Email
  - name: WEBUI_AUTH_TRUSTED_NAME_HEADER
    value: X-Forwarded-User

########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:
    {{<- range $manifest := .Values.deploykf_core.deploykf_auth.extraManifests >}}
    - {{< (tpl $manifest $) | quote >}}
    {{<- end >}}

  clusterDomain: cluster.local

  certManager:
    clusterIssuer:
      selfSigned:
        injectedConfigMapName: {{< .Values.deploykf_dependencies.cert_manager.clusterIssuer.selfSigned.injectedConfigMapName | quote >}}

  istio:
    namespace: {{< .Values.deploykf_dependencies.istio.namespace | quote >}}

  gateway:
    namespace: {{< .Values.deploykf_core.deploykf_istio_gateway.namespace | quote >}}
    serviceAccount: {{< .Values.deploykf_core.deploykf_istio_gateway.gatewayDeployment.serviceAccount.name | quote >}}
    name: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.name | quote >}}
    hostname: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.hostname | quote >}}
    tls:
      enabled: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.tls.enabled | conv.ToBool >}}
      clientsUseHttps: {{< .Values.deploykf_core.deploykf_istio_gateway.gateway.tls.clientsUseHttps | conv.ToBool >}}